#line 1 "/home/liangjs/study/compile/MiniCCompiler/src/parser/MiniC.yy.cpp"

#line 3 "/home/liangjs/study/compile/MiniCCompiler/src/parser/MiniC.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 117
#define YY_END_OF_BUFFER 118
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[524] =
    {   0,
        0,    0,   10,   10,  118,  116,  115,  115,  103,   69,
      109,  102,  116,   97,   98,  107,  106,   94,  105,  101,
      108,   49,   48,   95,   91,  110,   96,  111,  114,   46,
       99,  100,  112,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   92,  113,   93,
      104,   13,   13,   13,   15,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   10,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,  115,   90,   76,

       85,   77,    0,   59,    0,   74,   82,   72,   83,   73,
       84,   64,   16,   17,   75,   65,   49,    0,    0,   49,
       49,    0,   49,   48,   48,   48,   48,   81,   87,   89,
       88,   80,   46,   78,   46,   46,   46,   46,   46,   24,
       46,   46,   46,   46,   46,   31,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   79,   86,   13,
       13,   13,    0,   14,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    9,    8,   11,

        7,    1,    2,    3,    4,    5,    6,    0,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   62,    0,   59,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   64,   17,    0,
       65,    0,   63,   49,   49,   49,   49,    0,   47,   48,
       48,   48,   48,   71,   70,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   29,   46,   32,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       12,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   58,   57,   60,   56,
       50,   51,   52,   53,   54,   55,    0,    0,   64,    0,
       65,   63,   49,    0,    0,   47,    0,   47,   47,   48,
       46,   19,   20,   46,   46,   46,   46,   26,   27,   46,
       30,   33,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   44,   46,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   61,    0,    0,   47,   47,    0,   66,   47,   47,
       18,   21,   46,   46,   46,   28,   46,   35,   46,   46,
       46,   46,   46,   46,   42,   46,   45,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,    0,   67,    0,   68,   66,   47,   46,   46,
       25,   34,   36,   37,   38,   39,   40,   46,   46,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   67,   68,   46,   23,
       41,   46,   13,   13,   13,   13,   13,   13,   22,   43,
       13,   13,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   30,   29,   29,   29,   31,
       29,   29,   29,   29,   32,   29,   29,   33,   29,   29,
       34,   35,   36,   37,   29,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   29,   47,   48,   49,   50,
       51,   52,   29,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    4,    1,    5,    5,    5,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    6,    6,
        6,    6,    6,    1,    3,    1,    1,    5,    5,    5,
        5,    5,    5,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[534] =
    {   0,
        0,    0,   65,    0,  980,  981,  129,  131,  956,  981,
      955,  128,  128,  981,  981,  954,  125,  981,  126,  124,
      136,  149,  194,  981,  981,  116,  953,  121,  981,    0,
      981,  981,  952,  921,  120,  104,  106,  109,  922,  119,
      921,  929,  128,  910,  919,  917,  922,  981,  130,  981,
      981,    0,  175,  943,  182,  942,  165,  184,    0,    0,
      941,  178,    0,  180,  181,  191,  236,  281,    0,    0,
      173,  940,  192,    0,  337,    0,  398,    0,  939,  908,
      172,  119,  170,  174,  909,  184,  908,  916,  183,  897,
      906,  904,  909,    0,  183,    0,    0,  228,  981,  981,

      981,  981,  945,  981,  453,  981,  981,  981,  981,  981,
      981,  243,  981,    0,  981,  288,  199,  230,  262,  203,
      234,  937,  245,    0,  258,  235,  271,  928,  981,  981,
      981,  927,    0,  981,  907,  894,  909,  896,  902,  888,
      889,  886,  890,  887,  884,    0,  883,  887,  881,  884,
      195,  199,  888,  881,  221,  886,  885,  981,  981,    0,
      241,    0,  307,  981,    0,    0,    0,  922,    0,    0,
        0,    0,    0,    0,    0,  392,    0,  282,    0,  432,
      498,  412,  464,  272,  292,  540,  376,  569,  382,  294,
      396,  906,    0,    0,    0,  905,    0,  981,  981,  303,

      981,  981,  981,  981,  981,  981,  981,    0,    0,  885,
      872,  887,  874,  880,  866,  867,  864,  868,  865,  862,
        0,  861,  865,  859,  862,  360,  426,  866,  859,  243,
      864,  863,    0,    0,  981,  900,  899,  317,  898,  897,
      896,  895,  894,  893,  892,    0,  481,  981,    0,  515,
      981,  428,  546,  386,  981,  869,  850,    0,  489,  411,
      981,  867,  848,  981,  981,  857,  852,  840,  278,  854,
      852,  848,  840,  850,    0,  836,    0,  842,  829,  831,
      833,  840,  826,  824,  824,  836,  826,  830,  834,  826,
        0,  530,    0,  421,  586,    0,  467,  590,  431,    0,

      843,  824,  622,  521,  433,    0,  841,  822,    0,    0,
        0,  831,  826,  814,  414,  828,  826,  822,  814,  824,
        0,  810,    0,  816,  803,  805,  807,  814,  800,  798,
      798,  810,  800,  804,  804,  789,  981,  981,  981,  981,
      981,  981,  981,  981,  981,  981,  823,  488,  604,  505,
      625,  981,  981,  442,  459,  560,  612,  375,  470,  981,
      779,    0,    0,  770,  771,  758,  765,    0,    0,  757,
        0,    0,  758,  753,  765,  755,  759,  763,  762,  759,
      749,  754,    0,  752,  543,  639,  553,  653,    0,    0,
      685,  483,  563,  672,  377,  580,    0,  745,    0,    0,

      735,  731,  720,  726,    0,    0,  713,    0,    0,  713,
      710,  719,  708,  705,  710,  708,  702,  688,  692,    0,
      693,  981,  680,  703,  445,  981,  596,  712,  689,  670,
        0,    0,  664,  652,  653,    0,  643,    0,  647,  642,
      640,  611,  614,  612,    0,  596,    0,  727,  735,  595,
        0,  657,  739,  615,  589,    0,    0,  585,  562,  564,
        0,  552,    0,  556,  548,  545,  520,  511,  508,    0,
      493,    0,  660,  745,  688,  753,  981,  981,  483,  483,
        0,    0,    0,    0,    0,    0,    0,  488,  467,  691,
      761,  715,  767,    0,    0,  441,  417,    0,    0,    0,

        0,    0,    0,    0,  423,  375,  981,  981,  371,    0,
        0,  331,    0,    0,  284,    0,    0,  253,    0,    0,
        0,    0,  981,  815,  817,  823,  829,  835,  838,  843,
      235,  175,  170
    } ;

static const flex_int16_t yy_def[534] =
    {   0,
      523,    1,  523,    3,  523,  523,  523,  523,  523,  523,
      523,  523,  524,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  525,
      523,  523,  523,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  523,  523,  523,
      523,  526,  526,  526,  523,  526,  526,  527,  526,  526,
      526,  526,  526,  526,  526,  526,  526,  526,  526,  526,
      526,  526,  526,  526,  523,  526,  523,  526,  526,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,  526,  526,  526,  526,  523,  523,  523,

      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  528,  523,  523,   22,  523,  523,  523,
      523,  529,  523,   23,  523,  523,  523,  523,  523,  523,
      523,  523,  525,  523,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  523,  523,  526,
      526,  526,  523,  523,  526,  526,  526,  526,  526,  526,
      526,  526,  526,  526,  526,  526,  526,  530,  526,  526,
      526,  526,  526,  526,  526,  526,  526,  526,  526,  526,
      526,  526,  526,  526,  526,  526,   75,  523,  523,  523,

      523,  523,  523,  523,  523,  523,  523,  531,  526,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,  526,  526,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  532,  523,  523,  528,  523,
      523,  523,  523,  523,  523,  523,  523,  533,  529,  523,
      523,  523,  523,  523,  523,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      526,  526,  526,  530,  526,  526,  526,  526,  526,  526,

      526,  526,  526,  186,  526,  526,  526,  526,  526,  526,
      531,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  532,  523,  523,  523,
      523,  523,  523,  533,  533,  523,  523,  523,  523,  523,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  526,  526,  526,  526,  526,  526,
      526,  391,  526,  526,  526,  526,  526,   75,   75,   75,

       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  526,  526,  526,
      526,  526,  526,  526,  526,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,  523,  523,  523,  523,  523,  523,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  526,
      526,  526,  526,  526,  526,   75,   75,   75,   75,   75,

       75,   75,   75,   75,   75,   75,  523,  523,  525,  525,
      525,  525,  526,  526,   75,   75,   75,   75,  525,  525,
       75,   75,    0,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523
    } ;

static const flex_int16_t yy_nxt[1047] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   23,   24,
       25,   26,   27,   28,   29,   30,   30,   30,   30,   30,
       30,   30,   30,   31,    6,   32,   33,   30,   34,   35,
       36,   37,   38,   39,   30,   40,   30,   41,   30,   30,
       30,   30,   42,   43,   44,   45,   46,   47,   30,   30,
       30,   48,   49,   50,   51,   52,   53,    8,   54,   55,
       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   68,   69,   70,   71,   72,   73,   74,
       75,   75,   75,   75,   75,   75,   75,   75,   76,   77,

       78,   79,   75,   80,   81,   82,   83,   84,   85,   75,
       86,   75,   87,   75,   75,   75,   75,   88,   89,   90,
       91,   92,   93,   75,   75,   75,   94,   95,   96,   97,
       98,   98,   98,   98,  101,  104,  107,  128,  129,  109,
      112,  112,  112,  131,  132,  139,  113,  108,  110,  111,
      102,  114,  158,  141,  140,  142,  143,  136,  115,  144,
      214,  146,  105,  116,  137,  117,  117,  118,  147,  215,
      138,  166,  150,  151,  354,  119,  161,   98,  120,  347,
      121,  122,  152,  163,  163,  153,  164,  167,  103,  171,
      119,  169,  159,  173,  192,  193,  123,  176,  176,  176,

      172,  177,  174,  175,  121,  233,  178,  122,  116,  211,
      124,  124,  124,  179,  195,  196,  212,  216,  105,  217,
      119,  218,  213,  125,  219,  126,  221,  225,  226,   98,
       98,  523,  254,  222,  255,  119,  283,  227,  281,  311,
      228,  127,  161,   98,  116,  234,  118,  118,  118,  126,
      180,  284,  181,  181,  182,  282,  119,  523,  255,  112,
      112,  112,  183,  256,  262,  184,  287,  185,  186,  247,
      248,  119,  248,  252,  288,  252,  255,  183,  253,  253,
      253,  257,  263,  187,  247,  248,  249,  260,  333,  261,
      248,  185,  254,  522,  186,  180,  334,  188,  188,  188,

      255,  299,  261,  300,  112,  112,  112,  183,  163,  163,
      189,  164,  190,  261,  250,  251,  249,  251,  260,  200,
      200,  301,  183,  307,  339,  521,  261,  300,  191,  250,
      251,  364,  365,  238,  238,  251,  190,  160,  160,  302,
      160,  308,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  197,  197,  197,  160,  160,  160,  160,
      160,  160,  197,  197,  197,  197,  197,  197,  197,  197,
      160,  520,  160,  160,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  160,  160,

      160,  160,  198,  327,  429,  199,  454,  300,  176,  176,
      176,  305,  519,  306,  200,  200,  518,  255,  292,  293,
      328,  293,  430,  299,  455,  249,  180,  306,  182,  182,
      182,  300,  201,  292,  293,  202,  203,  306,  183,  293,
      204,  255,  261,  305,  253,  253,  253,  205,  176,  176,
      176,  306,  206,  183,  207,  249,  208,  236,  295,  296,
      237,  296,  300,  329,  306,  517,  261,  401,  402,  238,
      238,  516,  423,  295,  296,  297,  426,  297,  330,  296,
      298,  298,  298,  298,  298,  298,  300,  239,  306,  424,
      240,  241,  348,  423,  348,  242,  515,  349,  349,  349,

      426,  426,  243,  355,  349,  349,  349,  244,  512,  245,
      424,  246,  180,  449,  181,  181,  182,  425,  356,  357,
      358,  351,  351,  351,  183,  426,  350,  184,  350,  185,
      511,  351,  351,  351,  449,  392,  359,  510,  509,  183,
      357,  385,  506,  385,  358,  187,  386,  386,  386,  505,
      393,  394,  395,  185,  303,  504,  304,  304,  304,  386,
      386,  386,  253,  253,  253,  304,  304,  304,  396,  388,
      388,  388,  394,  352,  503,  352,  395,  304,  304,  304,
      304,  304,  304,  180,  502,  188,  188,  188,  352,  425,
      501,  426,  450,  352,  451,  183,  500,  387,  189,  387,

      190,  499,  388,  388,  388,  498,  298,  298,  298,  497,
      183,  451,  428,  428,  428,  426,  191,  389,  451,  389,
      349,  349,  349,  427,  190,  427,  451,  450,  428,  428,
      428,  248,  389,  248,  496,  451,  495,  389,  391,  391,
      391,  351,  351,  351,  495,  489,  248,  391,  391,  391,
      451,  248,  251,  488,  251,  386,  386,  386,  487,  391,
      391,  391,  391,  391,  391,  486,  293,  251,  293,  388,
      388,  388,  251,  453,  453,  453,  474,  474,  474,  485,
      296,  293,  296,  452,  484,  452,  293,  483,  453,  453,
      453,  473,  482,  473,  481,  296,  474,  474,  474,  480,

      296,  391,  391,  391,  476,  476,  476,  491,  491,  491,
      391,  391,  391,  479,  475,  448,  475,  478,  478,  476,
      476,  476,  391,  391,  391,  391,  391,  391,  428,  428,
      428,  493,  493,  493,  472,  471,  448,  470,  490,  477,
      490,  477,  469,  491,  491,  491,  492,  468,  492,  467,
      466,  493,  493,  493,  477,  453,  453,  453,  465,  477,
      464,  474,  474,  474,  463,  462,  494,  461,  494,  476,
      476,  476,  507,  460,  507,  459,  458,  491,  491,  491,
      508,  494,  508,  493,  493,  493,  494,  507,  513,  457,
      513,  456,  507,  447,  514,  508,  514,  446,  445,  444,

      508,  443,  442,  513,  441,  440,  439,  438,  513,  514,
      437,  436,  435,  434,  514,  103,  433,  103,  103,  103,
      103,  133,  133,  160,  432,  431,  160,  160,  160,  168,
      422,  168,  168,  168,  168,  249,  421,  249,  249,  249,
      249,  259,  259,  294,  420,  294,  294,  294,  294,  419,
      418,  417,  416,  415,  414,  413,  412,  411,  410,  409,
      408,  407,  406,  405,  404,  403,  400,  399,  398,  397,
      397,  390,  390,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  373,  372,  371,  370,  369,  368,
      367,  366,  363,  362,  361,  360,  360,  353,  353,  346,

      345,  344,  343,  342,  341,  340,  338,  337,  336,  335,
      332,  331,  326,  325,  324,  323,  322,  321,  320,  319,
      318,  317,  316,  315,  314,  313,  312,  310,  309,  291,
      290,  289,  286,  285,  280,  279,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  258,  235,  232,  231,  230,  229,  224,  223,  220,
      210,  209,  194,  170,  165,  162,  157,  156,  155,  154,
      149,  148,  145,  135,  134,  130,  106,  100,   99,  523,
        5,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,

      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523
    } ;

static const flex_int16_t yy_chk[1047] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        7,    7,    8,    8,   12,   13,   17,   26,   26,   19,
       20,   20,   20,   28,   28,   36,   21,   17,   19,   19,
       12,   21,   49,   37,   36,   37,   38,   35,   21,   38,
       82,   40,   13,   22,   35,   22,   22,   22,   40,   82,
       35,   57,   43,   43,  533,   22,   53,   53,   22,  532,
       22,   22,   43,   55,   55,   43,   55,   57,   58,   62,
       22,   58,   49,   64,   71,   71,   22,   65,   65,   65,

       62,   66,   64,   64,   22,   95,   66,   22,   23,   81,
       23,   23,   23,   66,   73,   73,   81,   83,   58,   83,
       23,   84,   81,   23,   84,   23,   86,   89,   89,   98,
       98,  117,  120,   86,  120,   23,  152,   89,  151,  531,
       89,   23,  161,  161,  118,   95,  118,  118,  118,   23,
       67,  152,   67,   67,   67,  151,  118,  117,  120,  112,
      112,  112,   67,  121,  126,   67,  155,   67,   67,  112,
      112,  118,  112,  119,  155,  119,  123,   67,  119,  119,
      119,  121,  126,   67,  112,  112,  178,  125,  230,  125,
      112,   67,  123,  518,   67,   68,  230,   68,   68,   68,

      123,  184,  127,  184,  116,  116,  116,   68,  163,  163,
       68,  163,   68,  125,  116,  116,  178,  116,  127,  200,
      200,  185,   68,  190,  238,  515,  127,  184,   68,  116,
      116,  269,  269,  238,  238,  116,   68,   75,   75,  185,
       75,  190,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,  512,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,

       75,   75,   77,  226,  358,   77,  395,  187,  176,  176,
      176,  189,  509,  189,   77,   77,  506,  254,  176,  176,
      226,  176,  358,  187,  395,  294,  182,  191,  182,  182,
      182,  187,   77,  176,  176,   77,   77,  189,  182,  176,
       77,  254,  260,  191,  252,  252,  252,   77,  180,  180,
      180,  191,   77,  182,   77,  294,   77,  105,  180,  180,
      105,  180,  299,  227,  305,  505,  260,  315,  315,  105,
      105,  497,  354,  180,  180,  183,  425,  183,  227,  180,
      183,  183,  183,  297,  297,  297,  299,  105,  305,  355,
      105,  105,  247,  354,  247,  105,  496,  247,  247,  247,

      425,  359,  105,  259,  348,  348,  348,  105,  489,  105,
      355,  105,  181,  392,  181,  181,  181,  359,  259,  259,
      259,  350,  350,  350,  181,  359,  250,  181,  250,  181,
      488,  250,  250,  250,  392,  304,  259,  480,  479,  181,
      259,  292,  471,  292,  259,  181,  292,  292,  292,  469,
      304,  304,  304,  181,  186,  468,  186,  186,  186,  385,
      385,  385,  253,  253,  253,  186,  186,  186,  304,  387,
      387,  387,  304,  253,  467,  253,  304,  186,  186,  186,
      186,  186,  186,  188,  466,  188,  188,  188,  253,  356,
      465,  356,  393,  253,  393,  188,  464,  295,  188,  295,

      188,  462,  295,  295,  295,  460,  298,  298,  298,  459,
      188,  396,  427,  427,  427,  356,  188,  298,  393,  298,
      349,  349,  349,  357,  188,  357,  450,  396,  357,  357,
      357,  349,  298,  349,  458,  396,  455,  298,  303,  303,
      303,  351,  351,  351,  454,  446,  349,  303,  303,  303,
      450,  349,  351,  444,  351,  386,  386,  386,  443,  303,
      303,  303,  303,  303,  303,  442,  386,  351,  386,  388,
      388,  388,  351,  452,  452,  452,  473,  473,  473,  441,
      388,  386,  388,  394,  440,  394,  386,  439,  394,  394,
      394,  423,  437,  423,  435,  388,  423,  423,  423,  434,

      388,  391,  391,  391,  475,  475,  475,  490,  490,  490,
      391,  391,  391,  433,  424,  391,  424,  430,  429,  424,
      424,  424,  391,  391,  391,  391,  391,  391,  428,  428,
      428,  492,  492,  492,  421,  419,  391,  418,  448,  428,
      448,  428,  417,  448,  448,  448,  449,  416,  449,  415,
      414,  449,  449,  449,  428,  453,  453,  453,  413,  428,
      412,  474,  474,  474,  411,  410,  453,  407,  453,  476,
      476,  476,  474,  404,  474,  403,  402,  491,  491,  491,
      476,  453,  476,  493,  493,  493,  453,  474,  491,  401,
      491,  398,  474,  384,  493,  476,  493,  382,  381,  380,

      476,  379,  378,  491,  377,  376,  375,  374,  491,  493,
      373,  370,  367,  366,  493,  524,  365,  524,  524,  524,
      524,  525,  525,  526,  364,  361,  526,  526,  526,  527,
      347,  527,  527,  527,  527,  528,  336,  528,  528,  528,
      528,  529,  529,  530,  335,  530,  530,  530,  530,  334,
      333,  332,  331,  330,  329,  328,  327,  326,  325,  324,
      322,  320,  319,  318,  317,  316,  314,  313,  312,  308,
      307,  302,  301,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,  280,  279,  278,  276,  274,  273,  272,
      271,  270,  268,  267,  266,  263,  262,  257,  256,  245,

      244,  243,  242,  241,  240,  239,  237,  236,  232,  231,
      229,  228,  225,  224,  223,  222,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  196,  192,  168,
      157,  156,  154,  153,  150,  149,  148,  147,  145,  144,
      143,  142,  141,  140,  139,  138,  137,  136,  135,  132,
      128,  122,  103,   93,   92,   91,   90,   88,   87,   85,
       80,   79,   72,   61,   56,   54,   47,   46,   45,   44,
       42,   41,   39,   34,   33,   27,   16,   11,    9,    5,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,

      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "MiniC.l"

#line 18 "MiniC.l"
#include <cstdio>
#include <cstring>
#include <string>
#include "MiniC.tab.hpp"
#include "symbol.h"

extern void yyerror(const char *);  /* prints grammar violation message */

std::string strbuf;

void comment(void);
int check_type(void);

#line 863 "/home/liangjs/study/compile/MiniCCompiler/src/parser/MiniC.yy.cpp"
#line 864 "/home/liangjs/study/compile/MiniCCompiler/src/parser/MiniC.yy.cpp"

#define INITIAL 0
#define INSTRING 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 33 "MiniC.l"


#line 1085 "/home/liangjs/study/compile/MiniCCompiler/src/parser/MiniC.yy.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 524 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 981 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 35 "MiniC.l"
{strbuf += '\a';}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 36 "MiniC.l"
{strbuf += '\b';}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 37 "MiniC.l"
{strbuf += '\f';}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 38 "MiniC.l"
{strbuf += '\n';}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 39 "MiniC.l"
{strbuf += '\t';}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 40 "MiniC.l"
{strbuf += '\v';}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 41 "MiniC.l"
{strbuf += '\\';}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 42 "MiniC.l"
{strbuf += '\'';}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 43 "MiniC.l"
{strbuf += '\"';}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 44 "MiniC.l"
{strbuf += '\?';}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 45 "MiniC.l"
{char c; sscanf(yytext, "\\%hho", &c); strbuf += c;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 46 "MiniC.l"
{char c; sscanf(yytext, "\\x%hhx", &c); strbuf += c;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 47 "MiniC.l"
{strbuf += yytext;}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 48 "MiniC.l"
{}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 49 "MiniC.l"
{yylval.vstr = strdup(strbuf.c_str()); BEGIN 0; return STR_CONSTANT;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "MiniC.l"
{ comment(); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "MiniC.l"
{ /* consume //-comment */ }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 54 "MiniC.l"
{ return(BREAK); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 55 "MiniC.l"
{ return(CASE); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 56 "MiniC.l"
{ return(CHAR); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 57 "MiniC.l"
{ return(CONST); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 58 "MiniC.l"
{ return(CONTINUE); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 59 "MiniC.l"
{ return(DEFAULT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 60 "MiniC.l"
{ return(DO); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 61 "MiniC.l"
{ return(DOUBLE); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 62 "MiniC.l"
{ return(ELSE); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 63 "MiniC.l"
{ return(ENUM); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 64 "MiniC.l"
{ return(FLOAT); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 65 "MiniC.l"
{ return(FOR); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 66 "MiniC.l"
{ return(GOTO); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 67 "MiniC.l"
{ return(IF); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 68 "MiniC.l"
{ return(INT); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 69 "MiniC.l"
{ return(LONG); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 70 "MiniC.l"
{ return(RETURN); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 71 "MiniC.l"
{ return(SHORT); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 72 "MiniC.l"
{ return(SIGNED); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 73 "MiniC.l"
{ return(SIZEOF); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 74 "MiniC.l"
{ return(STATIC); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 75 "MiniC.l"
{ return(STRUCT); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 76 "MiniC.l"
{ return(SWITCH); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 77 "MiniC.l"
{ return(TYPEDEF); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 78 "MiniC.l"
{ return(UNION); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 79 "MiniC.l"
{ return(UNSIGNED); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 80 "MiniC.l"
{ return(VOID); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 81 "MiniC.l"
{ return(WHILE); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 83 "MiniC.l"
{ return check_type(); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 85 "MiniC.l"
{ if (!isdigit(yytext[strlen(yytext)-1])) yyerror("{IS} not supported yet"); 
                                sscanf(yytext, "%x", &yylval.vint); return INT_CONSTANT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 87 "MiniC.l"
{ if (!isdigit(yytext[strlen(yytext)-1])) yyerror("{IS} not supported yet"); 
                                sscanf(yytext, "%d", &yylval.vint); return INT_CONSTANT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "MiniC.l"
{ if (!isdigit(yytext[strlen(yytext)-1])) yyerror("{IS} not supported yet"); 
                                sscanf(yytext, "%o", &yylval.vint); return INT_CONSTANT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 91 "MiniC.l"
{ yylval.vchar = '\a'; return CHAR_CONSTANT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 92 "MiniC.l"
{ yylval.vchar = '\b'; return CHAR_CONSTANT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 93 "MiniC.l"
{ yylval.vchar = '\f'; return CHAR_CONSTANT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 94 "MiniC.l"
{ yylval.vchar = '\n'; return CHAR_CONSTANT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 95 "MiniC.l"
{ yylval.vchar = '\t'; return CHAR_CONSTANT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 96 "MiniC.l"
{ yylval.vchar = '\v'; return CHAR_CONSTANT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 97 "MiniC.l"
{ yylval.vchar = '\\'; return CHAR_CONSTANT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 98 "MiniC.l"
{ yylval.vchar = '\''; return CHAR_CONSTANT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 99 "MiniC.l"
{ yylval.vchar = '\"'; return CHAR_CONSTANT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 100 "MiniC.l"
{ yylval.vchar = '\?'; return CHAR_CONSTANT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 101 "MiniC.l"
{ sscanf(yytext, "'\\%hho'", &yylval.vchar); return CHAR_CONSTANT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 102 "MiniC.l"
{ sscanf(yytext, "'\\x%hhx'", &yylval.vchar); return CHAR_CONSTANT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 103 "MiniC.l"
{ yylval.vchar = yytext[1]; return CHAR_CONSTANT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 105 "MiniC.l"
{ char c=tolower(yytext[strlen(yytext)-1]); if (c=='l'||c=='u') yyerror("{FS} not supported yet");
                                sscanf(yytext, "%lf", &yylval.vdouble); return DOUBLE_CONSTANT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 107 "MiniC.l"
{ char c=tolower(yytext[strlen(yytext)-1]); if (c=='l'||c=='u') yyerror("{FS} not supported yet");
                                sscanf(yytext, "%lf", &yylval.vdouble); return DOUBLE_CONSTANT; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 109 "MiniC.l"
{ char c=tolower(yytext[strlen(yytext)-1]); if (c=='l'||c=='u') yyerror("{FS} not supported yet");
                                sscanf(yytext, "%lf", &yylval.vdouble); return DOUBLE_CONSTANT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 111 "MiniC.l"
{ char c=tolower(yytext[strlen(yytext)-1]); if (c=='l'||c=='u') yyerror("{FS} not supported yet");
                                sscanf(yytext, "%lf", &yylval.vdouble); return DOUBLE_CONSTANT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 113 "MiniC.l"
{ char c=tolower(yytext[strlen(yytext)-1]); if (c=='l'||c=='u') yyerror("{FS} not supported yet");
                                sscanf(yytext, "%lf", &yylval.vdouble); return DOUBLE_CONSTANT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 115 "MiniC.l"
{ char c=tolower(yytext[strlen(yytext)-1]); if (c=='l'||c=='u') yyerror("{FS} not supported yet");
                                sscanf(yytext, "%lf", &yylval.vdouble); return DOUBLE_CONSTANT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 118 "MiniC.l"
{ BEGIN INSTRING; strbuf = ""; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 120 "MiniC.l"
{ return RIGHT_ASSIGN; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 121 "MiniC.l"
{ return LEFT_ASSIGN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 122 "MiniC.l"
{ return ADD_ASSIGN; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 123 "MiniC.l"
{ return SUB_ASSIGN; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 124 "MiniC.l"
{ return MUL_ASSIGN; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 125 "MiniC.l"
{ return DIV_ASSIGN; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 126 "MiniC.l"
{ return MOD_ASSIGN; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 127 "MiniC.l"
{ return AND_ASSIGN; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 128 "MiniC.l"
{ return XOR_ASSIGN; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 129 "MiniC.l"
{ return OR_ASSIGN; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 130 "MiniC.l"
{ return RIGHT_OP; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 131 "MiniC.l"
{ return LEFT_OP; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 132 "MiniC.l"
{ return INC_OP; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 133 "MiniC.l"
{ return DEC_OP; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 134 "MiniC.l"
{ return PTR_OP; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 135 "MiniC.l"
{ yylval.vint = 0; return AND_OP; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 136 "MiniC.l"
{ yylval.vint = 1; return OR_OP; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 137 "MiniC.l"
{ return LE_OP; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 138 "MiniC.l"
{ return GE_OP; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 139 "MiniC.l"
{ return EQ_OP; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 140 "MiniC.l"
{ return NE_OP; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 141 "MiniC.l"
{ return ';'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 142 "MiniC.l"
{ return '{'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 143 "MiniC.l"
{ return '}'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 144 "MiniC.l"
{ return ','; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 145 "MiniC.l"
{ return ':'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 146 "MiniC.l"
{ return '='; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 147 "MiniC.l"
{ return '('; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 148 "MiniC.l"
{ return ')'; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 149 "MiniC.l"
{ return '['; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 150 "MiniC.l"
{ return ']'; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 151 "MiniC.l"
{ return '.'; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 152 "MiniC.l"
{ return '&'; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 153 "MiniC.l"
{ return '!'; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 154 "MiniC.l"
{ return '~'; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 155 "MiniC.l"
{ return '-'; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 156 "MiniC.l"
{ return '+'; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 157 "MiniC.l"
{ return '*'; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 158 "MiniC.l"
{ return '/'; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 159 "MiniC.l"
{ return '%'; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 160 "MiniC.l"
{ return '<'; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 161 "MiniC.l"
{ return '>'; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 162 "MiniC.l"
{ return '^'; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 163 "MiniC.l"
{ return '|'; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 164 "MiniC.l"
{ return '?'; }
	YY_BREAK
case 115:
/* rule 115 can match eol */
YY_RULE_SETUP
#line 166 "MiniC.l"
{ /* whitespace separates tokens */ }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 167 "MiniC.l"
{ /* discard bad characters */ }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 169 "MiniC.l"
ECHO;
	YY_BREAK
#line 1738 "/home/liangjs/study/compile/MiniCCompiler/src/parser/MiniC.yy.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(INSTRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 524 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 524 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 523);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 169 "MiniC.l"


int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}

void comment(void)
{
    int c;

    while ((c = yyinput()) != 0)
        if (c == '*')
        {
            while ((c = yyinput()) == '*')
                ;

            if (c == '/')
                return;

            if (c == 0)
                break;
        }
    yyerror("unterminated comment");
}

int check_type(void)
{
    int type;
    void *p = LookupSymbol(yytext, &type);
    switch (type)
    {
    case TYPE_NAME:
        yylval.vptr = p;
        return TYPE_NAME;
    case ENUM_CONSTANT:
        yylval.vint = *(int*)p;
        return ENUM_CONSTANT;
    default:
        yylval.vstr = strdup(yytext);
        return IDENTIFIER;
    }
}

